name: 'License Approval'
description: 'Check if any license in use require approval'
outputs:
  license_report_json:
    description: "A report about licenses in JSON"
inputs:
  package_manager:
    description: 'Which package manager to check (comma separated)'
    required: true
    default: 'bundler'
  gh-token:
    description: 'Github secret to access private repository'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.package_manager }}
  env:
    ORG_GITHUB_TOKEN: ${{ inputs.gh-token }}
branding:
  icon: 'file-text'  
  color: 'purple'
